/** Maps the string icon names used in the shared MENU registry to lucide components. */
import {
  BadgePercent,
  BarChart3,
  BellRing,
  Box,
  Boxes,
  Building2,
  CalendarClock,
  Circle,
  ClipboardList,
  Wallet,
  Contact,
  Factory,
  FilePlus,
  FileText,
  Hammer,
  History,
  KeyRound,
  LayoutDashboard,
  PackageOpen,
  ListChecks,
  ListTree,
  Package,
  PackageCheck,
  PackagePlus,
  Percent,
  Receipt,
  ReceiptText,
  ScrollText,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Truck,
  UserCog,
  Users,
  Warehouse,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  ShoppingCart,
  ClipboardList,
  Contact,
  ListChecks,
  Percent,
  Receipt,
  Users,
  ReceiptText,
  Send,
  Package,
  PackageCheck,
  PackagePlus,
  PackageOpen,
  History,
  Box,
  ListTree,
  Factory,
  Hammer,
  Truck,
  ShoppingBag,
  Building2,
  Boxes,
  Warehouse,
  BarChart3,
  Settings,
  UserCog,
  ShieldCheck,
  KeyRound,
  ScrollText,
  SlidersHorizontal,
  FileText,
  FilePlus,
  BadgePercent,
  BellRing,
  CalendarClock,
  Wallet,
};

/** Resolve a menu icon name to a component, falling back to a neutral dot. */
export function getMenuIcon(name?: string): LucideIcon {
  return (name && ICONS[name]) || Circle;
}
