/**
 * PDF helpers. Documents (invoices, work orders, reports) are generated by the
 * API (pdfmake) for consistency and security; the client just downloads or
 * opens them. Add a `GET .../:id/pdf` endpoint on the backend and call these.
 */
import { api, downloadFile } from './api';

/**
 * True on iPhone/iPad (incl. iPadOS, which reports as "MacIntel" with touch).
 * iOS Safari blocks the usual "do async work, THEN download / window.open" flow
 * because the download/popup lands outside the original tap gesture — so it shows
 * "blocked". These helpers open the tab up-front (synchronously in the tap) instead.
 */
export function isIOS(): boolean {
  if (typeof navigator === 'undefined') return false;
  return /iP(hone|ad|od)/.test(navigator.userAgent) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
}

/** True on a phone/tablet (iOS or Android). Used to decide whether to route a
 *  generated PDF through the native share sheet (which preserves the filename)
 *  instead of a plain download / blob tab. */
export function isMobile(): boolean {
  if (typeof navigator === 'undefined') return false;
  return isIOS() || /Android/i.test(navigator.userAgent);
}

/** Share a named PDF file through the OS share sheet, if the platform supports
 *  sharing files. Returns true if the share sheet was shown (or the user handled
 *  it), false if file-sharing isn't available so the caller should fall back to a
 *  download/tab. A user-cancelled share still counts as handled (returns true) —
 *  we must NOT then also open a tab. */
async function tryShareFile(file: File, title: string): Promise<boolean> {
  const nav = typeof navigator !== 'undefined' ? (navigator as Navigator & { canShare?: (d: ShareData) => boolean }) : undefined;
  if (!nav?.canShare || !nav.share || !nav.canShare({ files: [file] })) return false;
  try {
    await nav.share({ files: [file], title });
    return true;
  } catch (err) {
    // User dismissed the sheet → handled, don't fall back to a tab.
    if (err instanceof DOMException && err.name === 'AbortError') return true;
    // Anything else (transient activation lost, target failed) → let the caller fall back.
    return false;
  }
}

/**
 * Hand a finished PDF to the OS share sheet, where WhatsApp, Mail and the rest
 * are targets. Returns false where the platform cannot share files, so the
 * caller can fall back.
 *
 * This is as close to "send this PDF on WhatsApp" as a browser gets: there is no
 * way to attach a file to WhatsApp from a link. `wa.me` / `whatsapp://` URLs
 * carry TEXT only — no API accepts an attachment — so anything that claims to
 * would in fact be sending a message with the file left behind.
 *
 * Must be called synchronously inside the click, before any await: the share
 * sheet needs the tap's transient activation.
 */
export function sharePdfFile(blob: Blob, filename: string, title?: string): Promise<boolean> {
  return tryShareFile(new File([blob], filename, { type: 'application/pdf' }), title || filename);
}

/** Call this SYNCHRONOUSLY inside a click handler (before any await) to reserve a
 *  tab iOS will trust for a PDF that's generated a moment later. Returns null off
 *  iOS (not needed there) or if the popup was blocked.
 *
 *  NOTE: only safe when the PDF is ready within a second or so. For the
 *  html2canvas bill captures it is NOT — see {@link savePdfBlob} — because the
 *  reserved tab outlives the transient activation and strands the user on a
 *  blank page. Those pages hand the finished blob to a fresh tap instead. */
export function preOpenPdfTab(): Window | null {
  return isIOS() ? window.open('', '_blank') : null;
}

/**
 * html2canvas scale factor for the bill captures.
 *
 * Desktop keeps 3× for maximum crispness. Phones drop to 2×: rasterising is
 * ~2× cheaper in both time and peak memory, which matters because an iPhone
 * takes seconds to rasterise a bill and Safari is quick to bin a large canvas
 * under memory pressure. 960 px × 2 = 1920 px across A4's ~587 pt of usable
 * width is still ~235 DPI, well beyond what any printer resolves.
 */
export function captureScale(): number {
  return isMobile() ? 2 : 3;
}

/**
 * Holds a tab opened synchronously in a click handler so a page reached via
 * client-side navigation right after can fill it in once its PDF is ready.
 *
 * Client-side routing (React Router) doesn't reload the document, so a tab
 * opened here survives the `navigate()` call that follows it — only a full page
 * reload would lose the reference. This is what lets "Preview PDF" in a list row
 * open a real tab (avoiding the popup blocker) even though the PDF itself is only
 * generated after navigating to and rendering the target page.
 */
let pendingPreviewTab: Window | null = null;

/** Call SYNCHRONOUSLY inside the click handler that is about to navigate to a
 *  page which will asynchronously build a PDF to preview there. */
export function reservePreviewTab(): void {
  pendingPreviewTab = window.open('', '_blank');
}

/** Consume the tab reserved by {@link reservePreviewTab}, if it's still open. */
export function takePendingPreviewTab(): Window | null {
  const tab = pendingPreviewTab;
  pendingPreviewTab = null;
  return tab && !tab.closed ? tab : null;
}

/**
 * Put a holding page in a reserved tab.
 *
 * The tab has to be opened inside the click (or the popup blocker eats it), but
 * the PDF behind it isn't ready for several seconds — the page must load, its
 * fonts and logo resolve, then html2canvas rasterises the invoice. Left as
 * `about:blank` the browser fronts a blank white tab for all of that, which
 * reads as "the preview opened an empty page and nothing happened".
 *
 * Same-origin `about:blank` inherits the opener's document, so this can be
 * written directly. Guarded because a user may close the tab at any moment.
 */
export function showPreviewPlaceholder(tab: Window | null, note = 'Preparing your preview…'): void {
  if (!tab || tab.closed) return;
  try {
    tab.document.open();
    tab.document.write(
      `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${note}</title>` +
        `<style>` +
        `html,body{height:100%;margin:0}` +
        `body{display:flex;align-items:center;justify-content:center;background:#f8fafc;` +
        `font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#334155}` +
        `.box{text-align:center}` +
        `.ring{width:34px;height:34px;margin:0 auto 14px;border:3px solid #dbeafe;border-top-color:#1d4ed8;` +
        `border-radius:50%;animation:spin .9s linear infinite}` +
        `@keyframes spin{to{transform:rotate(360deg)}}` +
        `p{margin:0;font-size:14px;font-weight:600}` +
        `small{display:block;margin-top:6px;font-size:12px;color:#64748b;font-weight:500}` +
        `</style></head><body><div class="box"><div class="ring"></div>` +
        `<p>${note}</p><small>This tab will show the PDF as soon as it is ready.</small>` +
        `</div></body></html>`,
    );
    tab.document.close();
  } catch {
    // Closed or otherwise unwritable — it just stays blank, as before.
  }
}

/**
 * Save/show a client-generated PDF blob (e.g. a jsPDF export).
 *
 * On mobile (iOS/Android) it first tries the native share sheet with a properly
 * NAMED file — this is what keeps the real filename instead of "Unknown", which
 * is what you get when a bare `blob:` URL (no filename) is shared from a tab.
 * If file-sharing isn't available it falls back to the previous behaviour:
 * iOS shows the PDF in `iosTab` (reserved via {@link preOpenPdfTab} inside the
 * tap); Android/desktop trigger a normal named download.
 *
 * MUST be called inside a live user gesture on iOS. `navigator.share()` needs
 * transient activation, which expires ~5 s after the tap — far less than the
 * 5–13 s an iPhone needs to rasterise a bill with html2canvas. Calling this
 * straight after a capture means share() throws NotAllowedError, we fall
 * through to the `blob:` tab, and the user is left staring at a blank page.
 * Callers that build the PDF asynchronously must therefore park the finished
 * blob and deliver it from a *fresh* tap.
 */
export async function savePdfBlob(blob: Blob, filename: string, iosTab?: Window | null): Promise<void> {
  const file = new File([blob], filename, { type: 'application/pdf' });

  // Mobile: the share sheet carries the file's real name. Only reachable while
  // the caller's tap is still "live" — see the transient-activation note above.
  if (isMobile() && (await tryShareFile(file, filename))) {
    iosTab?.close(); // the reserved tab is no longer needed
    return;
  }

  const url = URL.createObjectURL(blob);
  if (isIOS()) {
    if (iosTab && !iosTab.closed) {
      iosTab.location.href = url;
    } else {
      const w = window.open(url, '_blank');
      if (!w) window.location.href = url; // popup blocked entirely → same-tab view
    }
  } else {
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
  }
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

/** Download a server-generated PDF as a file. */
export function downloadPdf(url: string, fallbackName = 'document.pdf'): Promise<void> {
  return downloadFile(url, fallbackName);
}

/** Pull a filename out of a Content-Disposition header, if present. */
function filenameFromHeaders(headers: unknown): string | undefined {
  const cd = (headers as Record<string, string> | undefined)?.['content-disposition'];
  if (!cd) return undefined;
  const star = /filename\*=(?:UTF-8'')?([^;]+)/i.exec(cd);
  if (star?.[1]) return decodeURIComponent(star[1].trim().replace(/^"|"$/g, ''));
  const plain = /filename="?([^";]+)"?/i.exec(cd);
  return plain?.[1]?.trim();
}

/** Open a server-generated PDF — iOS-safe. On mobile it first offers the native
 *  share sheet with a properly NAMED file (so a shared/saved copy isn't "Unknown");
 *  otherwise it opens the PDF in a tab reserved up-front (synchronously in the tap
 *  gesture) so iOS Safari doesn't block it as a post-await popup. Pass `filename`
 *  for a friendly name; it falls back to the server's Content-Disposition. */
export async function openPdf(url: string, filename?: string): Promise<void> {
  // Reserve a tab now, inside the gesture; filled in (or closed) after the fetch.
  const tab = window.open('', '_blank');
  try {
    const res = await api.get(url, { responseType: 'blob' });
    const blob = res.data as Blob;
    if (isMobile()) {
      const name = filename || filenameFromHeaders(res.headers) || 'document.pdf';
      if (await tryShareFile(new File([blob], name, { type: 'application/pdf' }), name)) {
        tab?.close();
        return;
      }
    }
    const blobUrl = URL.createObjectURL(blob);
    if (tab && !tab.closed) tab.location.href = blobUrl;
    else window.location.href = blobUrl; // popup blocked → fall back to same tab
    // Revoke a little later so the tab has time to load it.
    setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
  } catch (e) {
    tab?.close();
    throw e;
  }
}

/** Consistent client-generated (jsPDF) download filename across Challan / Order /
 *  Quotation: "{Prefix}_{code}_{yyyy-MM-dd_HHmm}.pdf", e.g.
 *  "Challan_SSS-26-27-427_2026-07-19_1830.pdf". `code` falls back to `fallback`
 *  (e.g. "challan-42") when the record has no code yet. */
/** Resolve once the image data-URL has fully decoded into a bitmap. Used before
 *  `window.print()` so the (large) capture is painted first — mobile browsers
 *  otherwise snapshot the print view too early and produce a blank page. */
export function decodeImage(dataURL: string): Promise<void> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      // decode() gives a firmer "ready to paint" guarantee where supported.
      if (img.decode) img.decode().then(() => resolve(), () => resolve());
      else resolve();
    };
    img.onerror = () => resolve();
    img.src = dataURL;
  });
}

export function buildBillFilename(prefix: string, code: string | null | undefined, fallback: string): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  const d = new Date();
  const stamp = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}`;
  const safeCode = (code || fallback).replace(/[\\/:*?"<>|]/g, '-');
  return `${prefix}_${safeCode}_${stamp}.pdf`;
}
