/**
 * PDF helpers. Documents (invoices, work orders, reports) are generated by the
 * API (pdfmake) for consistency and security; the client just downloads or
 * opens them. Add a `GET .../:id/pdf` endpoint on the backend and call these.
 */
import { api, downloadFile } from './api';

/** Download a server-generated PDF as a file. */
export function downloadPdf(url: string, fallbackName = 'document.pdf'): Promise<void> {
  return downloadFile(url, fallbackName);
}

/** Open a server-generated PDF in a new browser tab. */
export async function openPdf(url: string): Promise<void> {
  const res = await api.get(url, { responseType: 'blob' });
  const blobUrl = URL.createObjectURL(res.data as Blob);
  window.open(blobUrl, '_blank', 'noopener,noreferrer');
  // Revoke a little later so the new tab has time to load it.
  setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
}

/** Consistent client-generated (jsPDF) download filename across Challan / Order /
 *  Quotation: "{Prefix}_{code}_{yyyy-MM-dd_HHmm}.pdf", e.g.
 *  "Challan_SSS-26-27-427_2026-07-19_1830.pdf". `code` falls back to `fallback`
 *  (e.g. "challan-42") when the record has no code yet. */
export function buildBillFilename(prefix: string, code: string | null | undefined, fallback: string): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  const d = new Date();
  const stamp = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}`;
  const safeCode = (code || fallback).replace(/[\\/:*?"<>|]/g, '-');
  return `${prefix}_${safeCode}_${stamp}.pdf`;
}
